---
output:
  html_document:
    toc: false
    toc_depth: 3
---

<div align="center">
# staR
Project Implementation  
Last update: 2021/01/25
</div>

### Preliminary notes

* Package 'factors' is not available for R version 4.0.2. An alternative has to be found;  

### Implemented Commands

* [recode](#rec)  
* [label variable](#labvar)  
* [generate/replace](#genrep)   
* [logit] (#logit)  
* [regress beta option](#beta)  
* [drop/keep](#dropkeep)  


#### 'recode' <a name="rec"></a>

The current version of 'recode' has still to be fully implemented (see the section 'Suggestions for Implementations'). The almost all the basic features of the command are in place and seem to work properly. The only option that has been implemented is 'generate'. The command recodes existing variables and allows for generating new variables. It allows for the specification of different rules, namely the one based single values (e.g. `recode x1 (1 2 3 = 1)`) or the one based on min/max (e.g. `recode x1 (1/3 = 1)`). The current version allows to recode multiple variables *if* no options (that is, 'generate' or, differently from original Stata syntax, 'gen') are included. As a consequence, the 'generate' option is allowed only if <span style='color:blue'><i>varlist</i></span> consists in a single variable, otherwise the command will return an error message. Currently, the command *does not* allow values labeling.  
Differently from previous speculations, the command fundamentally relies on the R base language. 

#### 'label variable' <a name="labvar"></a>  

The current version of 'label variable' has still to be fully implemented (see the section 'Suggestions for Implementations'). The basic features of the command work fine, and the command allows to specify the variable label. The command has been developed in order to handle further implementations (such as 'label values', 'label list', and so forth). 
 
#### 'replace' & 'generate' <a name="rep"></a>

The basic features of 'replace' have been implemented building on 'generate', thus both rely on the 'gen' parse type previously developed. Both commands support the 'if' statement, thus generating/replacing a variable according to the values of other variables. Both commands rely on the R base language and the packages `dplyr` (functions: `mutate()`, `select()`, and `left_join()`) and `labelled` (function: `var_label()`).

#### 'logit' <a name="logit"></a>  

The logit regression command ('logit') has been implemented relying on the 'regress.js' script. The command has been implemented relying on the R base language (function: `glm()`) and the `stargazer` package for the regression table visualization.  

#### 'regress beta option' <a name="beta"></a>

The linear regression command ('regress') now supports the 'beta' option. The command has been implemented fully relying on the staR background code, hence is fully integrated with the existing features of staR. Once specified, the options rescales the regression predictors using a base R language function (`scale()`) and the re-fits the regression model. 


#### 'drop' & 'keep' <a name="dropkeep"></a>

Commands 'drop' and 'keep' have been implemented using the R base language and the packages `dplyr` (function: `select()`), `labelled` (function: `var_label()`), and `expss` (function: `val_lab()`). Both commands support the 'if', thus turning the command syntax from '<b>drop</b>/<b>keep</b> <span style='color:blue'><i>varlist</i></span>' to '<b>drop</b>/<b>keep</b> <span style='color:blue'><b>if</b> <i>exp</i></span>'.   

### Suggestions for Implementations

#### Existing Commands

The two commands that at the current stage should be fully implemented are '**recode**' and '**label variable**'. Both rely on basic 'parseType' options ("label" and "recode"; see the 'command.html' file) that have been specified just for reproducing some general features of staR (e.g. the console feedback and the possibility to see and reproduce the command from the commands' list). However, both commands are parsed in the specific '.js' files, thus not allowing for a full integration with other staR features. Moreover, as already outlined above, 'recode' still does not support values labeling. Several alternatives have been explored but a solution has still to be found.  
Another implementation concerns '**generate**' and '**replace**'. It could be possible, at least hypothetically, to reduce the '.js' to one, following the same logic adopted for 'keep'/'drop'. Nonetheless, differently from the latter case, 'generate' and 'replace' scripts have more than few relevant differences, thus the "one-script reduction" would be a less straightforward process.  

#### Additional Commands

'graph box' (namely, boxplot) and 'alpha' scripts have been drafted but are still at a very preliminary stage of development, consequently have not been loaded on the staRjs dropbox folder. 

